KeyBindEvents.registry(event => {
  event.register('stompeez_dash', 'KEY_LEFT_ALT')
    .inGame()
    .category('key.categories.kubejs.thecatlord')
  event.register('weapon_special', 'KEY_LEFT_CONTROL')
    .inGame()
    .category('key.categories.kubejs.thecatlord')
  const KEY_ID = 'aeternitas_conversion'
  event.register('aeternitas_conversion', 'KEY_P')
    .inGame()
    .category('key.categories.kubejs.thecatlord')
  event.register('martyr_core_blast', 'KEY_I')
    .inGame()
    .category('key.categories.kubejs.contract_items')
  event.register('stompeez_step_height', 'KEY_P')
    .inGame()
    .category('key.categories.kubejs.thecatlord')
})
