Platform.mods.kubejs.name = 'TheCatLord'
StartupEvents.registry('creative_mode_tab', event => {
	event.create('plushies').icon(() => 'kubejs:cat_plush').displayName(('Plushies')).content(showRestrictedItems => [
    'kubejs:cat_plush',
    'kubejs:odins_plush',
    "kubejs:forest_plush",
    'kubejs:cotyn_plush',
    "kubejs:rex_plush",
    'kubejs:yaoi_plush',
    'kubejs:odins_shork'
  ])
})
StartupEvents.registry('block', event => {
  event.create('odins_plush','cardinal')
    .displayName('Odinshi Plushie')
    .item(item => {
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/odins_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
  event.create('cat_plush','cardinal')
    .displayName('TheCatLord0 Plushie')
    .item(item => {
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/cat_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
  event.create('forest_plush','cardinal')
    .displayName('ForestQueen558 Plushie')
    .item(item => {
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/forest_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
  event.create('cotyn_plush','cardinal')
    .displayName('Cotyn__ Plushie')
    .item(item => {
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/cotyn_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
  event.create('rex_plush','cardinal')
    .displayName('Rex_The_Knight55 Plushie')
    .item(item => {
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/rex_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
  event.create('yaoi_plush','cardinal')
    .displayName('Cat and Odin Plushies')
    .item(item => {
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/odin_cat_yaoi')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(0, 0, 5, 16, 12, 12)
  event.create('odins_shork','cardinal')
    .displayName('Odinshi Shork')
    .item(item => {
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/odins_shork')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
})
