Platform.mods.kubejs.name = 'TheCatLord'
StartupEvents.registry('creative_mode_tab', event => {
	event.create('plushies').icon(() => 'kubejs:cat_plush').displayName(('Plushies')).content(showRestrictedItems => [
    'kubejs:cat_plush',
    'kubejs:odins_plush',
    "kubejs:forest_plush",
    'kubejs:cotyn_plush'
  ])
})
StartupEvents.modifyCreativeTab('kubejs:tab', event => {
	event.remove('kubejs:odins_plush')
	event.remove('kubejs:cat_plush')
	event.remove('kubejs:forest_plush')
	event.remove('kubejs:cotyn_plush')
})
StartupEvents.registry('block', event => {
  event.create('odins_plush','cardinal')
    .displayName('Odinshi Plushie')
    .item(item => {
      item.unstackable()
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/odins_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
  event.create('cat_plush','cardinal')
    .displayName('TheCatLord0 Plushie')
    .item(item => {
      item.unstackable()
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/cat_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
  event.create('forest_plush','cardinal')
    .displayName('ForestQueen558 Plushie')
    .item(item => {
      item.unstackable()
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/forest_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
  event.create('cotyn_plush','cardinal')
    .displayName('Cotyn__ Plushie')
    .item(item => {
      item.unstackable()
      item.fireResistant(true)
      item.rarity('EPIC')
    })
    .parentModel('thecatlord:block/plushies/cotyn_plush')
    .opaque(false)
    .fullBlock(false)
    .renderType('cutout')
    .hardness(0.5)
    .soundType('wool')
    .box(1.5, 0, 3, 14.5, 16, 12)
})