#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=wing;size=0", "id=crystal;size=0", "id=rings;size=0", "id=waist;size=0", "id=face;size=0", "id=curio;size=0", "id=rune;size=2", "id=ring;size=10"]
