#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jun 03 20:30:18 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=miniature-shader-2.18.11.zip
