version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 128
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fluxnetworks = true
tide = true
farmersdelight = true
create_new_age = true
cataclysm = true
arseng = true
etched = true
quark = true
starbunclemania = true
irons_spellbooks = true
ars_technica = true
create_enchantment_industry = true
bits_n_bobs = true
mekanismgenerators = true
eidolon_repraised = true
functionalstorage = true
moonlight = true
rechiseledcreate = true
biomesoplenty = true
sophisticatedbackpacks = true
appflux = true
offroad = true
kubejs = true
cccbridge = true
rechiseledae = true
industrialforegoing = true
create = true
mekanism = true
aeronautics = true
simulated = true
gravestone = true
sfm = true
biomeswevegone = true
rechiseledae2 = true
ars_ocultas = true
occultism = true
minecraft = true
ars_additions = true
easy_villagers = true
create_dragons_plus = true
mowziesmobs = true
create_connected = true
iceandfire = true
irons_lib = true
createdeco = true
ratatouille = true
malum = true
ae2 = true
ars_elemental = true
ars_nouveau = true
irons_patreon_lib = true
computercraft = true
sauce = true
immersiveengineering = true
gaze = true
rechiseled = true
